language: go
go:
  - "1.15"

addons:
  ssh_known_hosts:
    - nugrohosamiyono.com:64000
  apt:
    packages:
      - ssh
      - sshpass
      - rsync

before_script:
  - cp deploy/domainesia/.htaccess.domainesia .htaccess
  - cp deploy/domainesia/.gitignore.domainesia .gitignore
  - rm -rf .git

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -avHP --exclude-from=.gitignore -e "sshpass -p$DOMAINESIA_SSH_PASSWORD ssh -p$DOMAINESIA_SSH_PORT" ./ $DOMAINESIA_SSH_USER@$DOMAINESIA_SSH_HOST:/home/$DOMAINESIA_SSH_USER/$DOMAINESIA_SSH_FOLDER_PATH
  on:
    branch: master
