language: go
go:
  - "1.15"

before_install:
  - sudo apt update
  - sudo apt -y install sshpass
  - sudo apt -y install ssh

deploy:
  provider: script
  script: bash deploy/domainesia/deploy.sh Televisi0810 64000 nugroho2 nugrohosamiyono.com ~/playground/gosampleapi
  on:
    branch: master
