language: go
go:
  - "1.15"

before_install:
  - sudo apt update
  - sudo apt -y install sshpass
  - sudo apt -y install ssh
  - sshpass -p Televisi0810 ssh -p 64000 nugroho2@nugrohosamiyono.com 

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/gosampleapi sshpass -p $DOMAINESIA_SSH_PASSWORD $DOMAINESIA_SSH_USER@$DOMAINESIA_SSH_HOST:~/playground/gosampleapi
  on:
    branch: master
