language: go
go:
- "1.15"

before_deploy: 
  - cp deploy/heroku/.gitignore.heroku ./.gitignore
  - git add .
  - git commit -m "Deploy To Heroku From Travis"
  
deploy:
  provider: heroku
  api_key: a265f92c-49ac-46c7-847c-be9843ae227b
  app: gosampleapi
  strategy: git