language: go
go:
  - "1.15"

addons:
  ssh_known_hosts: $DOMAINESIA_USER_HOST
  apt:
    packages:
      - ssh
      - sshpass
      - rsync

before_script:
  - cp ./deploy/domainesia/.gitignore.domainesia ./.gitignore

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -avHP --exclude-from=.gitignore --exclude=.git -e "sshpass -p$DOMAINESIA_SSH_PASSWORD ssh -p$DOMAINESIA_SSH_PORT" ./ $DOMAINESIA_SSH_USER@$DOMAINESIA_SSH_HOST:/home/$DOMAINESIA_SSH_USER/playground/gosampleapi
  on:
    branch: master
