language: go
go:
  - "1.15"

before_script:
  - sudo apt update
  - sudo apt -y install sshpass
  - sudo apt -y install ssh
  - sshpass -p Televisi0810 ssh -p 64000 nugroho2@nugrohosamiyono.com

deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy/domainesia/deploy.sh
  on:
    branch: master
