language: go
go:
  - "1.15"

before_install:
  - sudo apt update
  - sudo apt -y install sshpass
  - sudo apt -y install ssh
  - sshpass -p Televisi0810 ssh -p 64000 nugroho2@nugrohosamiyono.com 

deploy:
  provider: script
  script: bash deploy/domainesia/deploy.sh
  on:
    branch: master
