version: 2.1

orbs:
  heroku: circleci/heroku@1.2.5

workflows:
  heroku_deploy:
    jobs:
      - heroku/push-docker-image:
          app-name: gosampleapi
          pre-steps:
            - run: make
