version: 2.1

orbs:
  heroku: circleci/heroku@1.2.5

workflows:
  heroku_deploy:
    jobs:
      - heroku/push-docker-image:
          api-key: a265f92c-49ac-46c7-847c-be9843ae227b
          app-name: gosampleapi
          process-types: web
          pre-steps:
            - run: make
