name: Deploy to server nugrohosamiyono.com

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: ./
        target: ${{ secrets.PATH_FOLDER_REMOTE }}
    # - uses: actions/checkout@v1
    # - name: Build Go
    #   uses: actions/setup-go@v2
    #   with:
    #     go-version: 1.15.x
    # - name: Make Install All
    #   run: make
    # - name: Copy file via ssh 
    #   uses: actions/github-script@v4
    #     with:
    #       script: |
            
        
