name: Deploy to server nugrohosamiyono.com

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: ./
        target: ${{ secrets.PATH_FOLDER_REMOTE }}
    - name: Restart app
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: |
          cp ${{ secrets.PATH_FOLDER_REMOTE }}/deploy/domainesia/restart-app.sh.domainesia ${{ secrets.PATH_FOLDER_REMOTE }}/deploy/domainesia/restart-app.sh
          bash ${{ secrets.PATH_FOLDER_REMOTE }}/deploy/domainesia/restart-app.sh
        tryKeyboard: true
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        
